### ISSUE TITLE
Code in README.md does not work

### ISSUE THREAD

**Issue by kylepolich** [perminder-klair/resume-parser#1]
When running this code:
```
const ResumeParser = require('resume-parser');

// From file to file
ResumeParser
  .parseResumeFile('./files/resume.doc', './files/compiled') // input file, output dir
  .then(file => {
    console.log("Yay! " + file);
  })
  .catch(error => {
    console.error(error);
  });
```

I get this error:

```
TypeError: ResumeParser.parseResumeFile is not a function
    at /Users/kylepolich/git/ds/careers/parser/node_test_1/index.js:96:29
    at new Promise (<anonymous>)
    at parse_text_promise (/Users/kylepolich/git/ds/careers/parser/node_test_1/index.js:94:9)
    at /Users/kylepolich/git/ds/careers/parser/node_test_1/index.js:118:10
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by Motiab** [comment]
Try to use the previous commit, or try to diff it with the last one and get the right  parser function name ...

Moti

**Comment by perminder-klair** [comment]
Fixed in https://github.com/perminder-klair/resume-parser/pull/3
