### ISSUE TITLE
this.mime = mime.getType(file);

### ISSUE THREAD

**Issue by aadityak** [perminder-klair/resume-parser#14]
`D:\node-projects\resume-extractor>node test.js
2019-12-28T11:11:22+0530 <trace> processing.js:72 (extractTextFile) D:\node-projects\resume-extractor/files/1.pdf
D:\node-projects\resume-extractor\src\utils\libs\processing.js:120
  this.mime = mime.getType(file);
                   ^

TypeError: mime.getType is not a function
    at new PreparedFile (D:\node-projects\resume-extractor\src\utils\libs\processing.js:120:20)
    at D:\node-projects\resume-extractor\src\utils\libs\processing.js:83:18
    at D:\node-projects\resume-extractor\node_modules\textract\lib\extract.js:74:5
    at D:\node-projects\resume-extractor\node_modules\textract\lib\extractors\pdf.js:20:5
    at splitPages (D:\node-projects\resume-extractor\node_modules\pdf-text-extract\index.js:76:5)
    at ChildProcess.closeHandler (D:\node-projects\resume-extractor\node_modules\pdf-text-extract\index.js:106:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)`

**Comment by aneeshdua** [comment]
I have the same issue

**Comment by IshanDindorkar** [comment]
were any of you @aadityak / @aneeshdua, able to solve this problem? I am also struggling with it.

**Comment by n8jadams** [comment]
I believe the repository code has this fixed, but the latest repo code hasn't been published to npm.
